safe: false
port: 4000
base-url: /
url: http://schoewilliam.legtux.org

ftp_host: legtux.org
ftp_dir: /
ftp_username: schoewilliam

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

nodes:
- text: Arch Linux Forums
  url: https://bbs.archlinux.org/profile.php?id=55538
- text: DeviantArt
  url: http://schoewilliam.deviantart.com/
- text: Github
  url: https://github.com/Schoewilliam
- text: Mozillians
  url: https://mozillians.org/en-US/u/schoewilliam/
- text: reddit
  url: http://www.reddit.com/user/schoelcher/
- text: StatusNET
  url: https://status.vinilox.eu/schoewilliam

blogoliste:
- text: BlogiGor
  url: http://id-libre.org/blogigor
- text: Coreight
  url: http://coreight.com
- text: Dans la tÃªte du Linuxien
  url: http://tetedulinuxien.fr
- text: fabienwang
  url: http://fabienwang.fr
- text: Identitools
  url: http://identitools.fr
- text: Olivier Dossmann
  url: https://olivier.dossmann.net/blog/
- text: Postblue
  url: http://postblue.info
- text: Vinilox
  url: http://vinilox.eu

linkoliste:
- text: Legtux
  url: http://legtux.org/
- text: mart-e
  url: http://mart-e.be
- text: Le Hollandais Volant
  url: http://lehollandaisvolant.net/
- text: Source, Radio Campus Bruxelles
  url: http://src.radiocampus.be/

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
